services:
  - name: Google
    url: https://google123456.com
    max_response_time: 0.5

  - name: JSONPlaceholder
    url: https://jsonplaceholder.typicode.com/posts
    max_response_time: 1.0

alerting:
  telegram_enabled: false