services:
  - name: Google
    url: https://google.com
    max_response_time: 10

  - name: JSONPlaceholder
    url: https://jsonplaceholder.typicode.com/posts
    max_response_time: 10
    baseline: true
  
  - name: GitHub
    url: https://github.com
    max_response_time: 10

  - name: OpenAI
    url: https://openai.com
    max_response_time: 10

  - name: Reddit
    url: https://reddit.com
    max_response_time: 10

alerting:
  telegram_enabled: true
  telegram_bot_token: "8687331385:AAGFznGcYxBE8k8Z3r1T0FeI4aj-u4xncUU"
  telegram_chat_id: "1603171744"